# This file is auto-generated by build_alt_testlist.py
# Do not edit this file manually, as your changes will be overwritten.

from wrun_testlist_env import test_def

common_args = ' '

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_ref100_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_ref100_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_ref192_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF192 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_ref192_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF192 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_ref24_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF24 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_ref24_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF24 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_ref100_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_ref100_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_ref192_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF192 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_ref192_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF192 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_ref24_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF24 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_ref24_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF24 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_flip1_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,FLIP,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_flip1_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,FLIP,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_flip0_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,FLIP_RAM,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_flip0_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,FLIP_RAM,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_ref100_sscno_1lane_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +LANECFG=1LANE +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,LANE,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_ref100_sscno_1lane_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +LANECFG=1LANE +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,LANE,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen1_bringup_ref100_sscno_2lane_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +LANECFG=2LANE +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,LANE,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_rbr_100_no_ssc_u32_gen2_bringup_ref100_sscno_2lane_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=RBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +LANECFG=2LANE +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,LANE,RBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_ref100_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_ref100_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_ref192_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF192 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_ref192_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF192 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_ref24_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF24 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_ref24_sscno_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF24 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_ref100_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_ref100_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_ref192_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF192 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_ref192_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF192 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_ref24_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF24 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_ref24_sscen_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCEN +REFCLK=REF24 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_flip1_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,FLIP,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_flip1_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,FLIP,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_flip0_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,FLIP_RAM,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_flip0_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,DATA_PATH,FLIP_RAM,HBR 100M"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_ref100_sscno_1lane_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +LANECFG=1LANE +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M,LANE"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_ref100_sscno_1lane_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +LANECFG=1LANE +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M,LANE"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen1_bringup_ref100_sscno_2lane_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN1 +LANECFG=2LANE +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M,LANE"
)

test_def(
    testname    = "alt_mode_dp_hbr_100_no_ssc_u32_gen2_bringup_ref100_sscno_2lane_test",
    build       = "alt_mode_base_build",
    sim_args    = ' +DP_SPEED=HBR +define+SERDES_WIDTH=32 +SSCFLAG=SSCNO +REFCLK=REF100 +USB32_SPEED=USB32_GEN2 +LANECFG=2LANE +UVM_TESTNAME=cdn_alt_mode_phy_test_base +STANDARD=ALT +DP_TESTNAME=cdn_u4_dp_test_base +USB32_TESTNAME=cdn_u4_usb32_test_base ' + common_args,
    tag         = "ALT_MODE,BRINGUP,CORNER,DATA_PATH,HBR 100M,LANE"
)

