import wrun_testlist_env
import sys
import os

# ==============================================================================
#  Part 1: Capture data from source testlist files
# ==============================================================================

captured_tests = {}
def capture_test_data(**kwargs):
    source_file = sys._getframe(1).f_code.co_filename
    if source_file not in captured_tests:
        captured_tests[source_file] = []
    captured_tests[source_file].append(kwargs)

wrun_testlist_env.test_def = capture_test_data

try:
    import dp_testlist
    import usb32_testlist
except ImportError as e:
    print(f"ERROR: Could not import a testlist file. Make sure it's in the Python path. Details: {e}")
    sys.exit(1)

dp_key = next((k for k in captured_tests if 'dp_testlist' in k), None)
usb32_key = next((k for k in captured_tests if 'usb32_testlist' in k), None)
captured_dp_tests = captured_tests.get(dp_key, [])
captured_usb32_tests = captured_tests.get(usb32_key, [])

print(f"--- Captured {len(captured_dp_tests)} DP tests and {len(captured_usb32_tests)} USB32 tests. ---")

# ==============================================================================
#  Part 2: Define helper functions
# ==============================================================================

def parse_sim_args(arg_string=""):
    if not arg_string: return {}
    # --- MODIFICATION: Proactively filter out lane args during parsing ---
    parts = arg_string.strip().split()
    clean_parts = [p for p in parts if not p.startswith('+DP_LANE_NUM=') and not p.startswith('+USB32_LANE_NUM=')]
    clean_arg_string = ' '.join(clean_parts)
    
    return dict(part[1:].split('=', 1) for part in clean_arg_string.strip().split() if part.startswith('+') and '=' in part)

def format_sim_args(args_dict):
    return ' '.join(f"+{key}={value}" for key, value in args_dict.items())

# ==============================================================================
#  Part 3: Generate the final `alt_testlist.py` file
# ==============================================================================

output_filename = "alt_testlist.py"

try:
    with open(output_filename, "w") as f:
        f.write("# This file is auto-generated by build_alt_testlist.py\n")
        f.write("# Do not edit this file manually, as your changes will be overwritten.\n\n")
        f.write("from wrun_testlist_env import test_def\n\n")
        f.write("common_args = ' '\n\n")

        # Loop through all combinations
        for dp_config in captured_dp_tests:
            for usb32_config in captured_usb32_tests:
                
                # The parse_sim_args function now handles the removal
                dp_args = parse_sim_args(dp_config.get("sim_args"))
                usb32_args = parse_sim_args(usb32_config.get("sim_args"))

                final_args = {
                    **{k: v for k, v in dp_args.items() if k not in ["UVM_TESTNAME", "STANDARD"]},
                    **{k: v for k, v in usb32_args.items() if k not in ["UVM_TESTNAME", "STANDARD"]}
                }
                
                final_args.update({
                    "UVM_TESTNAME": "cdn_alt_mode_phy_test_base",
                    "STANDARD": "ALT",
                    "DP_TESTNAME": dp_args.get("UVM_TESTNAME", "MISSING_DP_TESTNAME"),
                    "USB32_TESTNAME": usb32_args.get("UVM_TESTNAME", "MISSING_USB32_TESTNAME")
                })

                # Tag Logic
                base_tags = {"ALT_MODE", "DATA_PATH"}
                dp_tags = {tag.strip() for tag in dp_config.get('tag', '').upper().split(',')}
                usb32_tags = {tag.strip() for tag in usb32_config.get('tag', '').upper().split(',')}
                all_tags = base_tags.union(dp_tags, usb32_tags)
                tags_to_remove = {"DP", "USB32", "JUNQIANG", ""}
                final_tags = all_tags - tags_to_remove
                combined_tag = ",".join(sorted(list(final_tags)))

                combined_testname = f"alt_mode_{dp_config['testname']}_{usb32_config['testname']}"
                
                final_sim_args_str = format_sim_args(final_args)

                f.write(
                    f"test_def(\n"
                    f"    testname    = \"{combined_testname}\",\n"
                    f"    build       = \"alt_mode_base_build\",\n"
                    f"    sim_args    = ' {final_sim_args_str} ' + common_args,\n"
                    f"    tag         = \"{combined_tag}\"\n"
                    f")\n\n"
                )

    print(f"--- Successfully generated '{output_filename}' ---")
    print(f"--- Total tests generated: {len(captured_dp_tests) * len(captured_usb32_tests)} ---")

except Exception as e:
    print(f"An error occurred during file generation: {e}")
