class c_gen(object):
    """ Container Class for CDB CONST File Creation """

    def __init__(self, ofile):
        self.ofile = ofile
        self.tab = "    "
        self.tab2 = self.tab+self.tab
        self.tab3 = self.tab+self.tab2
        self.tab4 = self.tab+self.tab3
        self.tab5 = self.tab+self.tab4
        
    def write(self, text):
        self.ofile.write(text+"\n")

    def write_header(self):
        self.write("//-----------------------------------------------------------------------------")
        self.write("//    This confidential and proprietary HDL soft description of a Hardware")
        self.write("//    component may be used only as authorized by a licensing agreement from")
        self.write("//    Cadence. In the event of publication, the following notice")
        self.write("//    is applicable:")
        self.write("//")
        self.write("//                       (C) COPYRIGHT 2019 Cadence")
        self.write("//                         ALL RIGHTS RESERVED")
        self.write("//")
        self.write("//     The entire notice above must be reproduced on all authorized")
        self.write("//     copies of this code.")
        self.write("//-----------------------------------------------------------------------------")
        self.write("//-----------------------------------------------------------------------------")
        self.write("//")
        self.write("// Filename        : c_parameters.c")
        self.write("// Version         : $")
        self.write("// Date / Time     : $")
        self.write("//")
        self.write("// Author          : <AUTOGENERATED>")
        self.write("// Abstract        : CDB register specific constants.")
        self.write("//")
        self.write("//-----------------------------------------------------------------------------")
        self.write("\n\n")
        self.write("#define BASE_ADDR   0x60040000\n")
        self.write("\n\n")

    def write_register(self, register):
        line   = self.tab+"#define XADDR_"+str(register.mnemonic).upper()+" ((volatile unsigned int *) (BASE_ADDR + "+hex(register.address)+"))"
        self.write(line)
