class cdb_const(object):
    """ Container Class for CDB CONST File Creation """

    def __init__(self, ofile):
        self.ofile = ofile
        self.tab = "    "
        self.tab2 = self.tab+self.tab
        self.tab3 = self.tab+self.tab2
        self.tab4 = self.tab+self.tab3
        self.tab5 = self.tab+self.tab4
        
    def write(self, text):
        self.ofile.write(text+"\n")

    def write_header(self, addr_width=16):
        self.write("//-----------------------------------------------------------------------------")
        self.write("//    This confidential and proprietary HDL soft description of a Hardware")
        self.write("//    component may be used only as authorized by a licensing agreement from")
        self.write("//    Cadence. In the event of publication, the following notice")
        self.write("//    is applicable:")
        self.write("//")
        self.write("//                       (C) COPYRIGHT 2014 Cadence")
        self.write("//                         ALL RIGHTS RESERVED")
        self.write("//")
        self.write("//     The entire notice above must be reproduced on all authorized")
        self.write("//     copies of this code.")
        self.write("//-----------------------------------------------------------------------------")
        self.write("//-----------------------------------------------------------------------------")
        self.write("//")
        self.write("// Filename        : pma_regs_const.v")
        self.write("// Version         : $")
        self.write("// Date / Time     : $")
        self.write("//")
        self.write("// Author          : <AUTOGENERATED>")
        self.write("// Abstract        : CDB register specific constants.")
        self.write("//")
        self.write("//-----------------------------------------------------------------------------")
        self.write("")
        self.write("// Lane address and multi-write address constants.")
        if (addr_width==18):
            self.write("`define TB_ADDR_LN_0                             18'b0000_0000_0000_0000_00")
            self.write("`define TB_ADDR_LN_1                             18'b0000_0010_0000_0000_00")
            self.write("`define TB_ADDR_LN_2                             18'b0000_0100_0000_0000_00")
            self.write("`define TB_ADDR_LN_3                             18'b0000_0110_0000_0000_00")
            self.write("`define TB_ADDR_LN_4                             18'b0000_1000_0000_0000_00")
            self.write("`define TB_ADDR_LN_5                             18'b0000_1010_0000_0000_00")
            self.write("`define TB_ADDR_LN_6                             18'b0000_1100_0000_0000_00")
            self.write("`define TB_ADDR_LN_7                             18'b0000_1110_0000_0000_00")
            self.write("`define TB_ADDR_MULTI_WR                         18'b0010_0000_0000_0000_00")
        else:
            self.write("`define TB_ADDR_LN_0                             16'b0000_0000_0000_0000")
            self.write("`define TB_ADDR_LN_1                             16'b0000_0010_0000_0000")
            self.write("`define TB_ADDR_LN_2                             16'b0000_0100_0000_0000")
            self.write("`define TB_ADDR_LN_3                             16'b0000_0110_0000_0000")
            self.write("`define TB_ADDR_LN_4                             16'b0000_1000_0000_0000")
            self.write("`define TB_ADDR_LN_5                             16'b0000_1010_0000_0000")
            self.write("`define TB_ADDR_LN_6                             16'b0000_1100_0000_0000")
            self.write("`define TB_ADDR_LN_7                             16'b0000_1110_0000_0000")
            self.write("`define TB_ADDR_MULTI_WR                         16'b0010_0000_0000_0000")

        self.write("")
        self.write("")
        self.write("`ifdef VER_LN_0")
        self.write("   `define APB_LANE_ADDR_OFFSET `TB_ADDR_LN_0")
        self.write("`elsif VER_LN_1")
        self.write("   `define APB_LANE_ADDR_OFFSET `TB_ADDR_LN_1")
        self.write("`elsif VER_LN_2")
        self.write("   `define APB_LANE_ADDR_OFFSET `TB_ADDR_LN_2")
        self.write("`elsif VER_LN_3")
        self.write("   `define APB_LANE_ADDR_OFFSET `TB_ADDR_LN_3")
        self.write("`elsif VER_LN_4")
        self.write("   `define APB_LANE_ADDR_OFFSET `TB_ADDR_LN_4")
        self.write("`elsif VER_LN_5")
        self.write("   `define APB_LANE_ADDR_OFFSET `TB_ADDR_LN_5")
        self.write("`elsif VER_LN_6")
        self.write("   `define APB_LANE_ADDR_OFFSET `TB_ADDR_LN_6")
        self.write("`elsif VER_LN_7")
        self.write("   `define APB_LANE_ADDR_OFFSET `TB_ADDR_LN_7")
        self.write("`else")
        self.write("   `define APB_LANE_ADDR_OFFSET `TB_ADDR_LN_0")
        self.write("`endif\n\n\n")

    def write_register(self, register, reg_width=16, addr_width=16):
        tb_addr_string   = "   `define TB_ADDR_"+str(register.mnemonic).upper()
        tb_rst_string    = "   `define TB_RST_"+str(register.mnemonic).upper()
        tb_mask_string   = "   `define TB_MASK_"+str(register.mnemonic).upper()
        tb_wrmask_string = "   `define TB_WRMASK_"+str(register.mnemonic).upper()
        tb_reg_width = str(reg_width)+"'h"
        tb_addr_width = str(addr_width)+"'h"

        address_hex_str = hex(register.address).replace("0x", tb_addr_width)
        comp_mask_hex_str = hex(register.compare_mask).replace("0x", tb_reg_width)
        update_mask_hex_str = hex(register.update_mask).replace("0x", tb_reg_width)

        self.write(tb_addr_string+"\t\t"+address_hex_str)
        if register.reset_value == "0xXXXX":
            self.write(tb_rst_string+"\t\t"+tb_reg_width+"XXXX")
        else:
            # remove L for long types
            rst_hex_str = hex(register.reset_value).replace("0x", tb_reg_width).replace('L', '');
            self.write(tb_rst_string+"\t\t"+rst_hex_str)
        self.write(tb_mask_string+"\t\t"+comp_mask_hex_str)
        self.write(tb_wrmask_string+"\t\t"+update_mask_hex_str)


