class parameter_gen(object):
    """ Container Class for CDB CONST File Creation """

    def __init__(self, ofile):
        self.ofile = ofile
        self.tab = "    "
        self.tab2 = self.tab+self.tab
        self.tab3 = self.tab+self.tab2
        self.tab4 = self.tab+self.tab3
        self.tab5 = self.tab+self.tab4
        
    def write(self, text):
        self.ofile.write(text+"\n")

    def write_header(self):
        self.write("//-----------------------------------------------------------------------------")
        self.write("//    This confidential and proprietary HDL soft description of a Hardware")
        self.write("//    component may be used only as authorized by a licensing agreement from")
        self.write("//    Cadence. In the event of publication, the following notice")
        self.write("//    is applicable:")
        self.write("//")
        self.write("//                       (C) COPYRIGHT 2019 Cadence")
        self.write("//                         ALL RIGHTS RESERVED")
        self.write("//")
        self.write("//     The entire notice above must be reproduced on all authorized")
        self.write("//     copies of this code.")
        self.write("//-----------------------------------------------------------------------------")
        self.write("//-----------------------------------------------------------------------------")
        self.write("//")
        self.write("// Filename        : cdb_parameters.v")
        self.write("// Version         : $")
        self.write("// Date / Time     : $")
        self.write("//")
        self.write("// Author          : <AUTOGENERATED>")
        self.write("// Abstract        : CDB register specific constants.")
        self.write("//")
        self.write("//-----------------------------------------------------------------------------")
        self.write("\n\n")

    def write_register(self, register, width=16):
        line   = "   parameter  p_"+str(register.mnemonic).lower()+" = "+hex(register.address).replace("0x", str(width)+"'h")+";"

        # remove L for long types
        line1  = "   logic ["+str(width-1)+":0] p_"+str(register.mnemonic).lower()+"_reg = "+hex(register.reset_value).replace("0x", str(width)+"'h").replace('L','')+";"

        self.write(line)
        self.write(line1)
