class rstruct_gen(object):
    """ Container Class for CDB CONST File Creation """

    def __init__(self, ofile):
        self.ofile = ofile
        self.tab = "   "
        self.tab2 = self.tab+self.tab
        self.tab3 = self.tab+self.tab2
        self.tab4 = self.tab+self.tab3
        self.tab5 = self.tab+self.tab4
        
    def write(self, text):
        self.ofile.write(text+"\n")

    def write_header(self):
        self.write("//-----------------------------------------------------------------------------")
        self.write("//    This confidential and proprietary HDL soft description of a Hardware")
        self.write("//    component may be used only as authorized by a licensing agreement from")
        self.write("//    Cadence. In the event of publication, the following notice")
        self.write("//    is applicable:")
        self.write("//")
        self.write("//                       (C) COPYRIGHT 2020 Cadence")
        self.write("//                         ALL RIGHTS RESERVED")
        self.write("//")
        self.write("//     The entire notice above must be reproduced on all authorized")
        self.write("//     copies of this code.")
        self.write("//-----------------------------------------------------------------------------")
        self.write("//-----------------------------------------------------------------------------")
        self.write("//")
        self.write("// Filename        : rstruct.sv")
        self.write("// Version         : $")
        self.write("// Date / Time     : $")
        self.write("//")
        self.write("// Author          : <AUTOGENERATED>")
        self.write("// Abstract        : CDB register specific constants.")
        self.write("//")
        self.write("//-----------------------------------------------------------------------------")
        self.write("`ifndef CDN_REG_PACKAGE")
        self.write("`define CDN_REG_PACKAGE")
        self.write("\n")

    def write_pkg(self):
        line = "package reg_package;\n"
        self.write(line)

    def write_pkg_end(self):
        line  = "endpackage  // reg_package\n"
        line += "`endif\n"
        self.write(line)
        

    def write_enums(self, registers):
        first  = True
        line   = self.tab+"typedef enum logic [17:0] { \n"
        for reg in registers:
            if not first :
                line+=",\n"
            line += self.tab2+str(reg.mnemonic).upper()+" = "+hex(reg.address).replace('0x', "18'h")
            first = False
        line += self.tab+"} reg_mnemonics; \n\n\n"
        self.write(line)

    def write_reg_struct(self):
        line  = self.tab+"typedef struct { \n"
        line += self.tab2+" string mnemonic;\n"
        line += self.tab2+" logic [17:0] address;\n"
        line += self.tab2+" logic [31:0] reset_value;\n"
        line += self.tab2+" logic [31:0] update_mask;\n"
        line += self.tab2+" logic [31:0] compare_mask;\n"
        line += self.tab2+" logic [31:0] value;\n"
        line += self.tab+"} reg_struct; \n\n"
        line += self.tab+"typedef reg_struct reg_array[integer];\n\n"
        self.write(line)

    def write_function_begin(self, tab, tab1):
        line   = tab+"function reg_array get_reg_array();\n"
        line  += tab1+"reg_struct tmp_reg;\n"
        self.write(line)

    def write_end(self, tab):
        line = tab+"end\n"
        self.write(line)

    def write_function_body(self, tab, register):
        line  = tab+'tmp_reg.mnemonic     = "'+str(register.mnemonic).upper()+'";\n'
        line += tab+'tmp_reg.address      = '+hex(register.address).replace('0x', "18'h")+";\n"
        line += tab+'tmp_reg.reset_value  = '+hex(register.reset_value).replace('0x', "32'h")+";\n"
        line += tab+'tmp_reg.update_mask  = '+hex(register.update_mask).replace('0x', "32'h")+";\n"
        line += tab+'tmp_reg.compare_mask = '+hex(register.compare_mask).replace('0x', "32'h")+";\n"
        line += tab+'tmp_reg.value        = '+hex(register.reset_value).replace('0x', "32'h")+";\n"
        line += tab+"get_reg_array["+hex(register.address).replace('0x', "18'h")+"] = tmp_reg;\n"
        self.write(line)

    def write_function(self, registers):
        self.write_function_begin(self.tab, self.tab2)
        for reg in registers:
            self.write_function_body(self.tab2, reg)
        line = self.tab+"endfunction\n\n"
        self.write(line)


     
    def write_rstruct_file(self, registers):
        self.write_header()
        self.write_pkg()
        self.write_reg_struct()
        self.write_function(registers)
        self.write_enums(registers)
        self.write_pkg_end()
        
