
+incdir+${PHY_VERIF_AREA}/agents/cdn_apb
+incdir+${PHY_VERIF_AREA}/agents/reset_agent
+incdir+${PHY_VERIF_AREA}/agents/cdn_jtag
+incdir+${PHY_VERIF_AREA}/agents/cdn_jtag_1687
+incdir+${PHY_VERIF_AREA}/base_code/src
+incdir+${PHY_VERIF_AREA}/base_code/include
+incdir+${PHY_VERIF_AREA}/base_code/env
+incdir+${PHY_VERIF_AREA}/agents/clk_agent
+incdir+${PHY_VERIF_AREA}/agents/usb4
+incdir+${PHY_VERIF_AREA}/agents/usb4/usb4_sequence_item
+incdir+${PHY_VERIF_AREA}/agents/usb32
+incdir+${PHY_VERIF_AREA}/agents/usb32/usb32_sequence_item
+incdir+${PHY_VERIF_AREA}/agents/dp
+incdir+${PHY_VERIF_AREA}/agents/pcie
+incdir+${PHY_VERIF_AREA}/agents/serdes
+incdir+${PHY_VERIF_AREA}/agents/pipe/cdn_message_bus
+incdir+${PHY_VERIF_AREA}/base_code/tests
+incdir+${PHY_VERIF_AREA}/tests
+incdir+${PHY_VERIF_AREA}/tests/usb4_tests
+incdir+${PHY_VERIF_AREA}/tests/usb32_tests
+incdir+${PHY_VERIF_AREA}/tests/dp_tests
+incdir+${PHY_VERIF_AREA}/tests/pcie_tests
+incdir+${PHY_VERIF_AREA}/tests/alt_mode_tests
+incdir+${PHY_VERIF_AREA}/tests/pipe_tests
+incdir+${PHY_VERIF_AREA}/tests/reg_tests
+incdir+${PHY_VERIF_AREA}/tests/bring_up_base_test
+incdir+${PHY_VERIF_AREA}/seq_lib/usb4_sequences
+incdir+${PHY_VERIF_AREA}/seq_lib/usb32_sequences
+incdir+${PHY_VERIF_AREA}/seq_lib/dp_sequences
+incdir+${PHY_VERIF_AREA}/seq_lib/pcie_sequences
+incdir+${PHY_VERIF_AREA}/seq_lib/phy_reg_seq
+incdir+${PHY_VERIF_AREA}/seq_lib/bring_up_seq
+incdir+${PHY_VERIF_AREA}/top/sram
+incdir+${PHY_VERIF_AREA}/top
+incdir+${PHY_VERIF_AREA}/seq_lib/pipe_sequences
+incdir+${DENALI}/ddvapi/sv/hdl_interfaces/cdn_apb 
+incdir+${DENALI}/ddvapi/sv/uvm/cdn_apb/examples 
+incdir+${DENALI}/ddvapi/sv/uvm/cdn_apb 
+incdir+${DENALI}/ddvapi/sv 
+incdir+${CDN_VIP_ROOT}/tools.lnx86/abvip/apb3/rtl 
${CDN_VIP_ROOT}/tools.lnx86/abvip/apb3/rtl/apb3_monitor.sv 
+incdir+${PHY_VERIF_AREA}/reg_model 
//+incdir+${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb4_phy_top_reg/uvmreg 
//+incdir+${PHY_VERIF_AREA}/common_ips/rst_lib_rtl
+incdir+${PHY_VERIF_AREA}/scripts/pg_scripts

+incdir+${DENALI}/ddvapi/sv/uvm/usb4
+incdir+${DENALI}/ddvapi/sv/uvm/pcie 
+incdir+${DENALI}/ddvapi/sv/uvm/usb 
+incdir+${DENALI}/ddvapi/sv/uvm/dp 
+incdir+${DENALI}/ddvapi/sv/uvm/pipephy
+incdir+${PHY_VERIF_AREA}/u4_vip/examples/multiProtocol/uvmConfigPipeExamplePhyDut
+incdir+${PHY_VERIF_AREA}/u4_vip/examples/multiProtocol/uvmConfigPipeExamplePhyDut/example_common
+incdir+${PHY_VERIF_AREA}/u4_vip/examples/example_common/config_uvm
+incdir+${DENALI}/ddvapi/sv/uvm/pipephy/examples/example_common

${DENALI}/ddvapi/sv/denaliMem.sv
${DENALI}/ddvapi/sv/denaliCdn_apb.sv
${DENALI}/ddvapi/sv/uvm/cdn_apb/cdnApbUvmTop.sv
${DENALI}/ddvapi/sv/hdl_interfaces/cdn_apb/cdnApb3Interface.sv
 
${DENALI}/ddvapi/sv/denaliUsb4.sv 
${DENALI}/ddvapi/sv/denaliPcie.sv 
${DENALI}/ddvapi/sv/denaliUsb.sv 
${DENALI}/ddvapi/sv/denaliDp.sv 
${DENALI}/ddvapi/sv/denaliPipephy.sv 
${DENALI}/ddvapi/sv/uvm/usb4/cdnUsb4UvmTop.sv
${DENALI}/ddvapi/sv/uvm/pcie/cdnPcieUvmTop.sv 
${DENALI}/ddvapi/sv/uvm/usb/cdnUsbUvmTop.sv 
${DENALI}/ddvapi/sv/uvm/dp/cdnDpUvmTop.sv 
${DENALI}/ddvapi/sv/uvm/pipephy/cdnPipephyUvmTop.sv 

${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/dpActLttpr4LnDfp.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/pcieActEp.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usbActEmbComp.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/dpActLttpr4LnUfp.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/pcieActRc.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usbActDevComp.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usbActEmbHubComp.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/dpActSnk.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/dpActSrc.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usb4PipephyActHostSuperWrapper.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usb4PipephyActHost.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/cdnPipephyMac.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usb4PipephyPsvHostSuperWrapper.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usb4PipephyPsv.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/cdnPipephyMacMon.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usb4PipephyActDevSuperWrapper.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/cdnPipephyPcsPma.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usb4ActRetimerSuperWrapper.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usb4ActRetimer.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usb4ActDevSuperWrapper.sv 
${PHY_VERIF_AREA}/u4_vip/examples/example_common/soma_uvm/usb4ActDev.sv 
//${PHY_VERIF_AREA}/u4_vip/examples/multiProtocol/uvmConfigPipeExamplePhyDut/cdnUsb4UvmUserTb.sv


${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdns_uvmreg_utils_pkg_pma_rx_lane_registers.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdns_uvmreg_utils_pkg_pma_tx_lane_registers.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdns_uvmreg_utils_pkg_phy_pcs_cmn_registers.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdns_uvmreg_utils_pkg_phy_pcs_lane_registers.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdns_uvmreg_utils_pkg_phy_pma_cmn_registers.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdns_uvmreg_utils_pkg_phy_pma_lane_registers.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdns_uvmreg_utils_pkg_pma_cmn_registers.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdns_uvmreg_utils_pkg_illegal_registers.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdn_phy_pcs_cmn_regs_rdb.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdn_phy_pcs_lane_regs_rdb.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdn_phy_pma_cmn_regs_rdb.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdn_phy_pma_lane_regs_rdb.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdn_pma_rx_lane_regs_rdb.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdn_pma_tx_lane_regs_rdb.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdn_pma_cmn_regs_rdb.sv
${PHY_VERIF_AREA}/reg_model/reg_model_cdn_usb_phy_top_reg/uvmreg/cdn_illegal_regs_rdb.sv
${PHY_VERIF_AREA}/top/tb_param.sv
${PHY_VERIF_AREA}/agents/serdes/serdes_pkg.sv
${PHY_VERIF_AREA}/agents/clk_agent/clk_if_pkg.sv
${PHY_VERIF_AREA}/agents/clk_agent/clk_pkg.sv
${PHY_VERIF_AREA}/agents/cdn_jtag/cdn_jtag_pkg.sv
${PHY_VERIF_AREA}/agents/cdn_jtag_1687/cdn_jtag_1687_pkg.sv
${PHY_VERIF_AREA}/agents/reset_agent/cdn_reset_pkg.sv
${PHY_VERIF_AREA}/base_code/include/cdn_phy_package.sv
${PHY_VERIF_AREA}/agents/pipe/cdn_message_bus/cdn_message_bus_pkg.sv
${PHY_VERIF_AREA}/agents/usb32/cdn_u4_usb32_port_types.sv
${PHY_VERIF_AREA}/agents/usb4/cdn_u4_usb4_port_types.sv
${PHY_VERIF_AREA}/agents/usb32/cdn_u4_usb32_package.sv
${PHY_VERIF_AREA}/agents/usb4/cdn_u4_usb4_package.sv
${PHY_VERIF_AREA}/agents/dp/cdn_u4_dp_package.sv
${PHY_VERIF_AREA}/agents/pcie/cdn_u4_pcie_port_types.sv
${PHY_VERIF_AREA}/agents/pcie/cdn_u4_pcie_package.sv


// Add register model files after all dependencies
${PHY_VERIF_AREA}/reg_model/cdn_usb_phy_top_regmodel.sv


${PHY_VERIF_AREA}/tests/test_package.sv
${PHY_VERIF_AREA}/top/sram/dpram.v
${PHY_VERIF_AREA}/top/sram/sram.sv
${PHY_VERIF_AREA}/top/sram/sram_wrapper.sv
${PHY_VERIF_AREA}/top/cdn_phy_tb_top.sv
