#!/usr/bin/perl
# +---------------------------------------------------------------------------+
# |  Copyright (c) 2013-2025 Cadence Design Systems Inc. ALL RIGHTS RESERVED. |
# |                                                                           |
# |   These coded instructions, statements, and computer programs             |
# |   are the copyrighted works and confidential proprietary                  |
# |   information of Tensilica Inc.  They may not be modified,                |
# |   copied, reproduced, distributed, or disclosed to third                  |
# |   parties in any manner, medium, or form, in whole or in part,            |
# |   without the prior written consent of Tensilica Inc.                     m
# +---------------------------------------------------------------------------+

use Cwd; 
my $cwd = cwd();
$cwd =~ s/\//\\\//g;
system("sed -i 's/cfg_dir =.*\$/cfg_dir = \"$cwd\";/g' ./lib/Params.pm");
system("sed -i 's/lib_dir =.*\$/lib_dir = \"$cwd\";}/g' ./scripts/run_stg");
system("./scripts/bld_stg");

