+incdir+${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/wrappers/Xttop.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/wrappers/Xtensa.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/ClkGate.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/Control.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/Decoder.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/DAlign.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/DStLdByp.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/DataTlb.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/ExternInt.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/MemBankCtrl.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/LSElement.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/LoadStore.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/ClkGate.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/TIE.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/IAlign.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/InstFetch.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/DataTlb.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/InstTlb.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/PCUnit.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/OCD.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/PCandIFetch.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/ResetStaging.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/core/Datapath.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/primitives/primitives.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/debug/Debug.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/debug/AccessPort.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/xtensa/debug/FaultReporter.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/ecc.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/apb2sram.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/dram2apb.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/idram_arb.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/sram_initialize.v
${PHY_WORK_AREA}/trunk/design/rtl/rtl_xtensa/uc.v


${PHY_WORK_AREA}/trunk/design/reuse/rtl_phy_misc_components/phy_clk_gate.v
${PHY_WORK_AREA}/trunk/design/reuse/rtl_phy_misc_components/phy_reset_sync.v
${PHY_WORK_AREA}/trunk/design/reuse/rtl_phy_misc_components/phy_scan_mux.v
